### ISSUE TITLE
Tracking issue for missing Batch Op Interface

### ISSUE THREAD

**Issue by Pangoraw** [EnzymeAD/Enzyme-JAX#152]
NOTE: Strikethrough ops are deliberately not implemented because the default broadcasting behavior of enzyme batch is enough.

- [ ] StableHLO
  - [ ] ~AbsOp~
  - [ ] ~AddOp~
  - [ ] ~AfterAllOp~
  - [ ] AllGatherOp
  - [ ] AllReduceOp
  - [ ] AllToAllOp
  - [ ] ~AndOp~
  - [ ] ~Atan2Op~
  - [ ] BatchNormGradOp
  - [ ] BatchNormInferenceOp
  - [ ] BatchNormTrainingOp
  - [ ] ~BitcastConvertOp~
  - [ ] BroadcastInDimOp
  - [ ] CaseOp
  - [ ] CbrtOp
  - [ ] CeilOp
  - [ ] CholeskyOp
  - [ ] ~ClampOp~
  - [ ] CollectiveBroadcastOp
  - [ ] CollectivePermuteOp
  - [ ] ~CompareOp~
  - [ ] ~ComplexOp~
  - [ ] CompositeOp
  - [ ] ConcatenateOp
  - [x] ConstantOp
  - [ ] ~ConvertOp~
  - [ ] ConvolutionOp
  - [ ] ~CosineOp~
  - [ ] ~ClzOp~
  - [ ] CustomCallOp
  - [ ] ~DivOp~
  - [ ] DotGeneralOp
  - [ ] DynamicBroadcastInDimOp
  - [ ] DynamicConvOp
  - [ ] DynamicGatherOp
  - [ ] DynamicIotaOp
  - [ ] DynamicPadOp
  - [ ] DynamicReshapeOp
  - [ ] DynamicSliceOp
  - [ ] DynamicUpdateSliceOp
  - [ ] ~ExpOp~
  - [ ] Expm1Op
  - [ ] FftOp
  - [ ] FloorOp
  - [ ] GatherOp
  - [ ] GetDimensionSizeOp
  - [ ] GetTupleElementOp
  - [ ] IfOp
  - [ ] ~ImagOp~
  - [ ] InfeedOp
  - [ ] IotaOp
  - [ ] IsFiniteOp
  - [ ] ~LogOp~
  - [ ] ~Logp1Op~
  - [ ] ~LogisticOp~
  - [ ] MapOp
  - [ ] ~MaxOp~
  - [ ] ~MinOp~
  - [ ] ~MulOp~
  - [ ] ~NegateOp~
  - [ ] ~NotOp~
  - [ ] OptimizationBarrierOp
  - [ ] ~OrOp~
  - [ ] OutfeedOp
  - [ ] PadOp
  - [ ] PartitionIdOp
  - [ ] ~PopcntOp~
  - [ ] ~PowOp~
  - [ ] ~RealOp~
  - [ ] RecvOp
  - [ ] ReduceOp
  - [ ] ReducePrecisionOp
  - [ ] ReduceScatterOp
  - [ ] ReduceWindowOp
  - [ ] ~RemainderOp~
  - [ ] ReplicaIdOp
  - [ ] ReshapeOp
  - [ ] ReverseOp
  - [ ] RngOp
  - [ ] RngBitGeneratorOp
  - [ ] ~RoundOp~
  - [ ] ~RoundNearestEvenOp~
  - [ ] ~RsqrtOp~
  - [ ] ScatterOp
  - [ ] SelectOp
  - [ ] SelectAndScatterOp
  - [ ] SendOp
  - [ ] ~ShiftLeftOp~
  - [ ] ~ShiftRightArithmeticOp~
  - [ ] ~ShiftRightLogicalOp~
  - [ ] SignO~p~
  - [ ] ~SineOp~
  - [ ] SliceOp
  - [ ] SortOp
  - [ ] ~SqrtOp~
  - [ ] ~SubtractOp~
  - [ ] ~TanhOp~
  - [x] TransposeOp
  - [ ] TriangularSolveOp
  - [ ] TupleOp
  - [ ] UniformDequantizeOp
  - [ ] UniformQuantizeOp
  - [ ] WhileOp
  - [ ] ~XorOp~
  - [ ] Deprecated operations in StableHLO
    - [ ] BroadcastOp
    - [ ] CreateTokenOp
    - [ ] CrossReplicaSumOp
    - [ ] DotOp
    - [ ] EinsumOp
    - ~TorchIndexSelectOp~
    - [ ] UnaryEinsumOp
- [ ] CHLO
  - [ ] Binary Element-wise Operations
    - [ ] ~BroadcastAddOp~
    - [ ] ~BroadcastAtan2Op~
    - [ ] ~BroadcastDivOp~
    - [ ] ~BroadcastMaxOp~
    - [ ] ~BroadcastMinOp~
    - [ ] ~BroadcastMulOp~
    - [ ] ~BroadcastNextAfterOp~
    - [ ] ~BroadcastPolygammaOp~
    - [ ] ~BroadcastPowOp~
    - [ ] ~BroadcastRemOp~
    - [ ] ~BroadcastShiftLeftOp~
    - [ ] ~BroadcastShiftRightArithmeticOp~
    - [ ] ~BroadcastShiftRightLogicalOp~
    - [ ] ~BroadcastSubOp~
    - [ ] ~BroadcastZetaOp~
  - [ ] Binary Logical Element-wise Operations
    - [ ] ~BroadcastAndOp~
    - [ ] ~BroadcastOrOp~
    - [ ] ~BroadcastXorOp~
  - [ ] Non-broadcasting Binary Operations
    - [ ] NextAfterOp
    - [ ] PolygammaOp
    - [ ] ZetaOp
  - [ ] `ComplexOp`
  - [ ] Unary Element-wise Operations
    - [ ] ~AcosOp~
    - [ ] ~AcoshOp~
    - [ ] ~AsinOp~
    - [ ] ~AsinhOp~
    - [ ] ~AtanOp~
    - [ ] ~AtanhOp~
    - [ ] ~BesselI1eOp~
    - [ ] ~ConjOp~
    - [ ] ~CoshOp~
    - [ ] ~SinhOp~
    - [ ] ~TanOp~
    - [ ] ~ConstantOp~ (shared with `StableHLO_ConstantOp`)
    - [ ] ~ConstantLikeOp~
    - [ ] ~DigammaOp~
    - [ ] ~ErfOp~
    - [ ] ~ErfInvOp~
    - [ ] ~ErfcOp~
    - [ ] ~IsInfOp~
    - [ ] ~IsNegInfOp~
    - [ ] ~IsPosInfOp~
    - [ ] LgammaOp
  - [ ] `BroadcastCompareOp`
  - [ ] `BroadcastSelectOp`
  - [ ] `TopKOp`

**Comment by mofeing** [comment]
> ... because the default broadcasting behavior of enzyme batch is enough.

Do you mean unrolling or leave the op unchanged?

**Comment by Pangoraw** [comment]
The batch pass will take the original op:

```mlir
%0 = stablehlo.add %arg0, %arg1 : tensor<10xf32>
```

and just prepend the broadcasted dimensions (_e.g._ 20x4):

```mlir
%0 = stablehlo.add %arg0, %arg1 : tensor<20x4x10xf32>
```

This is the default behavior for all ops unless they implement `BatchOpInterface`.

**Comment by wsmoses** [comment]
whileop definitely shouldn't be unrolled here in most cases [since it almost always has a number of iterations fixed by a constant aka non data-dependent value]

**Comment by avik-pal** [comment]
Should `CustomCallOp` always fallback to the looped version?

**Comment by wsmoses** [comment]
tenatively I think so, it at minimum feels like a better default [more likely to not error]

**Comment by joelberkeley** [comment]
Would you mind listing the caveats to these implementations? I've hit two different errors using batch with reduce: one to do with limited op support (it doesn't like `\x,y => y + x`, the order matters); the other to do with disallowed "neutral" term

**Comment by wsmoses** [comment]
yeah, though also @joelberkeley I'm of the opinion that we should fix things to never give an incorrect answer [throwing an error instead] and if that is the case it's a bug
